### ISSUE TITLE
Book crashes client

### ISSUE THREAD

**Issue by royalcw** [AEnterprise/Eureka#40]
When facing towards the air and opening the book, the client kicks the user from the server.  When the book is opened towards a nearby block (and the block is within clickable range), the book opens with no issues.  This looks to be a server related issue as seen by the Server log since the client log contains nothing about the issue.  Server is a home server running Windows 7, Java 1.8.0v45.  I don't think it is a specific java issue because the Eureka book opens fine when "used" on a nearby block.

Eureka version:  EUREKA-1.7.10-3.0.2
ModPack:  AT Launcher Resonant Rise 3.2.6.3

Server Log at the time of disconnect::
[20:49:22 WARN]: Failed to handle packet for /192.168.0.200:63395
java.lang.NullPointerException
     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:918) ~[nh.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

Client log results at the time of disconnect:
[27/5/2015 20:49:22 PM] [20:49:22] [Netty Client IO #0/INFO] [THAUMCRAFT]: Restoring client configs.
[27/5/2015 20:49:22 PM] [20:49:22] [Netty Client IO #0/INFO] [simplyjetpacks]: Loading configuration files
[27/5/2015 20:49:22 PM] [Client thread/INFO] [journeymap]: Mapping halted in **USERSDIR**\Instances\TestPack\journeymap\data\mp\LocalHost\DIM0
[27/5/2015 20:49:22 PM] [Client thread/INFO] [FML]: Applying holder lookups
[27/5/2015 20:49:22 PM] [Client thread/WARN] [FML]: Unable to lookup CompactMachines:interfaceblock for public static org.dave.CompactMachines.block.BlockCM org.dave.CompactMachines.init.ModBlocks.interfaceblock. Is there something wrong with the registry?
[27/5/2015 20:49:22 PM] [Client thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[27/5/2015 20:49:22 PM] [Client thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[27/5/2015 20:49:22 PM] [Client thread/INFO] [FML]: Holder lookups applied
[27/5/2015 20:49:26 PM] [Client thread/INFO] [Mekanism]: VoiceServer: Stopping client connection...
[27/5/2015 20:49:26 PM] [Client thread/INFO] [Mekanism]: Finished loading Cardboard Box blacklist (loaded 0 entries)
[27/5/2015 20:49:26 PM] [Client thread/INFO] [Mekanism]: Reloaded config.

**Comment by Cuppycake** [comment]
This is happening on our server as well using version 3.0.2

[09:46:11 WARN]: Failed to handle packet for /192.168.1.6:51836
java.lang.NullPointerException
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:918) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[09:46:11 INFO]: CuppyCake lost connection: Internal server error

**Comment by AEnterprise** [comment]
sorry for not replying sooner, i am not sure what is heapening here cause it works fine for me and alot of others, i'll contact the RR devs and try to narow down the cause

**Comment by Cuppycake** [comment]
It doesn't disconnect or crash on Single Player. Only on a server It seems.
